#!/bin/bash

# install the script
cp ./plate /usr/local/bin/plate
chmod 755 /usr/local/bin/plate

# copy the template projects to the config
CONFIGDIR=/home/${SUDO_USER}/.config/plate/templates
mkdir -p ${CONFIGDIR}
cp -r ./bash ${CONFIGDIR}/bash
cp -r ./c ${CONFIGDIR}/c
cp -r ./cpp ${CONFIGDIR}/cpp
